# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.

  config.vm.define "devops-box" do |devbox|
    devbox.vm.box = "ubuntu/bionic64"
    devbox.vm.network "private_network", ip: "55.55.55.5"
    devbox.vm.synced_folder "../", "/home/vagrant/http4s-multipart-image-upload-example"

    devbox.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus   = 4  
    end

    devbox.vm.provision "shell", path: "./scripts/install.sh"
  end

end
